drm/msm: Fix compilation error when CONFIG_DEBUG_FS undefined
Fixes the following compilation error when CONFIG_DEBUG_FS undefined:

CC [M]  drivers/gpu/drm/msm/adreno/a5xx_gpu.o
../drivers/gpu/drm/msm/adreno/a5xx_gpu.c:863:3: error: unknown field ‘show’ specified in initializer
../drivers/gpu/drm/msm/adreno/a5xx_gpu.c:863:11: error: ‘a5xx_show’ undeclared here (not in a function)
../drivers/gpu/drm/msm/adreno/a5xx_gpu.c:863:3: warning: excess elements in struct initializer [enabled by default]
../drivers/gpu/drm/msm/adreno/a5xx_gpu.c:863:3: warning: (near initialization for ‘funcs.base’) [enabled by default]
make[5]: *** [drivers/gpu/drm/msm/adreno/a5xx_gpu.o] Error 1
make[4]: *** [drivers/gpu/drm/msm] Error 2
make[4]: *** Waiting for unfinished jobs....

Fixes: b5f103ab98c7 ("drm/msm: gpu: Add A5XX target support")
Cc: Jordan Crouse <jcrouse@codeaurora.org>
Cc: Rob Clark <robdclark@gmail.com>
Reviewed-by: Emil Velikov <emil.l.velikov@gmail.com>
Acked-by: Jordan Crouse <jcrouse@codeaurora.org>
Signed-off-by: Sean Paul <seanpaul@chromium.org>
Link: http://patchwork.freedesktop.org/patch/msgid/20170306202722.9301-4-seanpaul@chromium.org